name: Trigger Docs on Tag

on:
  push:
    tags: ['v*']

permissions:
  actions: write

jobs:
  trigger-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'docs.yaml',
              ref: 'master'
            })
