name: Pinact

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'

permissions:
  contents: read

jobs:
  pinact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: false
      - uses: suzuki-shunsuke/pinact-action@v2.0.0
        with:
          app_id: ${{ vars.BOT_APP_ID }}
          app_private_key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
